### ISSUE TITLE
throws NullReferenceException when expression is just a parameter

### ISSUE THREAD

**Issue by danielcrenna** [pvginkel/Expressions#17]
expression = "p1"; //<--- the entire equation is just a variable called 'p1'
context.Variables["p1"] = 100;
result should be 100 but an exception is thrown instead

**Comment by pvginkel** [comment]
This is quite a basic sample and should just work. I expect the issue is with the rest of the code. Could you please post a full code sample?

**Comment by danielcrenna** [comment]
I think it has to do with not being able to use the advertised 3-phase step, where I can bind in between expression declaration and binding invocation.

```
const string expression = "p1";
var variables = new string[] { "p1" };
var values = new object[] { 100 };
```

The version that throws:

```
            DynamicExpression expr = new DynamicExpression(expression, ExpressionLanguage.Flee);
            var context = new ExpressionContext();
            if (variables != null && values != null)
            {
                for (var i = 0; i < variables.Length; i++)
                    context.Variables.Add(variables[i], values[i]);
            }
            var bound = expr.Bind(context);
            return bound.Invoke();
```

The version that works:

```
            DynamicExpression expr = new DynamicExpression(expression, ExpressionLanguage.Flee);
            var context = new ExpressionContext();
            if (variables != null && values != null)
            {
                for (var i = 0; i < variables.Length; i++)
                    context.Variables.Add(variables[i], values[i]);
            }
            return expr.Invoke(context);
```

**Comment by pvginkel** [comment]
Ah, now I understand. The purpose of the `Bind` method is to get a cached version of the expression that already has the parameter types bound. This is used when you know that the types of the parameters will always be the same and saves you from having to rebind every time you call `Invoke`. The solution is to change the first code sample to the following:

```
DynamicExpression expr = new DynamicExpression(expression, ExpressionLanguage.Flee);
var context = new ExpressionContext();
if (variables != null && values != null)
{
    for (var i = 0; i < variables.Length; i++)
        context.Variables.Add(variables[i], values[i]);
}
var bound = expr.Bind(context);
return bound.Invoke(context);
```

(i.e. adding `context` to `Invoke`).

The point of this is that you can re-use `bound` and call `Invoke` on it with other context. Note that the types of `Bind` and `Invoke` differ. `Bind` takes a `IBindingContext` and `Invoke` takes a `IExecutionContext`, and `ExpressionContext` implements both. You can use `ExpressionContext` for calling `Invoke`, but you could also implement `IExecutionContext` yourself to get a simpler class to be used when calling `Invoke`.
